### ISSUE TITLE
Failed. card1.jpg could not be rectified :(

### ISSUE THREAD

**Issue by ZabeehUllah** [shakex/card-rectification#2]
I am running your demo code but it gives me **"Failed. card1.jpg could not be rectified :( "** error. Can you explain why is it giving me this error?

**Comment by alaamh** [comment]
I try it, same error :(

**Comment by zrz520** [comment]
me too!

**Comment by shakex** [comment]
> I am running your demo code but it gives me **"Failed. card1.jpg could not be rectified :( "** error. Can you explain why is it giving me this error?

pls use opencv-python==3.4.9.33 and try again. Note that you can also set `debug = True` in rectify,py and make a new dir named `debug` in the root dir to see the images when doing the processing.

**Comment by shakex** [comment]
![image](https://user-images.githubusercontent.com/17232603/187415216-d5030714-9b5d-4df7-bf5f-77f8e1376471.png)
it seems that there is a mistake when doing this commitment. 😅

**Comment by uzair004** [comment]
@shakex code gets stuck while finding contourArea. 
`cv2.contourArea(cnts[i])`
Tried using cv2.moments['m00'] to get area but still a problem.

There is also problem at sorted method, in particular, in lambda function passed to sorted method
