### ISSUE TITLE
error running the demo

### ISSUE THREAD

**Issue by alaamh** [shakex/card-rectification#3]
I have clone the repository as is, however getting error: 
`Failed. card1.jpg could not be rectified :(`
`cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/shapedescr.cpp:280: error: (-215:Assertion failed) count >= 0 && (depth == CV_32F || depth == CV_32S) in function 'arcLength'`

**Comment by alaamh** [comment]
the fix I have implemented is to replace the line #204 in rectify.py

`cnts = cnts[0] if imutils.is_cv2() else cnts[1]`

with

`cnts = cnts[0] if imutils.is_cv2(or_better=True) else cnts[1]`

**Comment by shakex** [comment]
> the fix I have implemented is to replace the line #204 in rectify.py
> 
> `cnts = cnts[0] if imutils.is_cv2() else cnts[1]`
> 
> with
> 
> `cnts = cnts[0] if imutils.is_cv2(or_better=True) else cnts[1]`

thx. i'll fix it later.

**Comment by uzair004** [comment]
> the fix I have implemented is to replace the line #204 in rectify.py
> 
> `cnts = cnts[0] if imutils.is_cv2() else cnts[1]`
> 
> with
> 
> `cnts = cnts[0] if imutils.is_cv2(or_better=True) else cnts[1]`

it worked, Thanks
